"""BQ-K1-KITFILL-001 — material-family kit hole catalog (charter authority)."""

from __future__ import annotations

from typing import Any

BATCH_REL = "tools/mcp/schemas/examples/bq_k1_kitfill_batch_v1.json"
CHARTER_REL = "src/dev/design_bq_k1_kitfill_charter_v1.md"

# Priority order from plan_building_quality_v1.md BQ-K1.
K1_JOBS: tuple[dict[str, Any], ...] = (
    {
        "module_id": "roof_brick_gable_2u",
        "material_family": "brick",
        "category": "roof",
        "style_packs": ["style_colonial", "style_victorian"],
        "operation": "module_roof",
        "material_profile": "brick_red_01",
        "grid_units": [2, 1],
        "dimensions_m": {"w": 8.0, "h": 1.8, "d": 4.0, "pitch_deg": 32},
        "replaces_slots": {"style_colonial": "roof_default", "style_victorian": "roof_default"},
    },
    {
        "module_id": "door_brick_residential_1u",
        "material_family": "brick",
        "category": "door",
        "style_packs": ["style_colonial", "style_victorian"],
        "operation": "module_door",
        "material_profile": "brick_red_01",
        "grid_units": [1, 1],
        "dimensions_m": {"w": 1.2, "h": 2.2, "d": 0.2},
        "replaces_slots": {"style_colonial": "door_default", "style_victorian": "door_default"},
    },
    {
        "module_id": "win_brick_1u",
        "material_family": "brick",
        "category": "window",
        "style_packs": ["style_colonial", "style_victorian"],
        "operation": "module_window",
        "material_profile": "brick_red_01",
        "grid_units": [1, 1],
        "dimensions_m": {"w": 1.2, "h": 1.4, "d": 0.15},
        "replaces_slots": {"style_colonial": "window_1u", "style_victorian": "window_1u"},
    },
    {
        "module_id": "win_brick_2u",
        "material_family": "brick",
        "category": "window",
        "style_packs": ["style_colonial", "style_victorian"],
        "operation": "module_window",
        "material_profile": "brick_red_01",
        "grid_units": [2, 1],
        "dimensions_m": {"w": 2.4, "h": 1.6, "d": 0.15},
        "replaces_slots": {"style_colonial": "window_2u", "style_victorian": "window_2u"},
    },
    {
        "module_id": "roof_wood_gable_2u",
        "material_family": "wood",
        "category": "roof",
        "style_packs": ["style_rural"],
        "operation": "module_roof",
        "material_profile": "wood_plank_01",
        "grid_units": [2, 1],
        "dimensions_m": {"w": 8.0, "h": 1.6, "d": 4.0, "pitch_deg": 30},
        "replaces_slots": {"style_rural": "roof_default"},
    },
    {
        "module_id": "win_wood_1u",
        "material_family": "wood",
        "category": "window",
        "style_packs": ["style_rural"],
        "operation": "module_window",
        "material_profile": "wood_plank_01",
        "grid_units": [1, 1],
        "dimensions_m": {"w": 1.0, "h": 1.2, "d": 0.12},
        "replaces_slots": {"style_rural": "window_1u"},
    },
    {
        "module_id": "win_wood_2u",
        "material_family": "wood",
        "category": "window",
        "style_packs": ["style_rural"],
        "operation": "module_window",
        "material_profile": "wood_plank_01",
        "grid_units": [2, 1],
        "dimensions_m": {"w": 2.0, "h": 1.2, "d": 0.12},
        "replaces_slots": {"style_rural": "window_2u"},
    },
    {
        "module_id": "roof_concrete_flat_2u",
        "material_family": "concrete",
        "category": "roof",
        "style_packs": ["style_modern", "style_military"],
        "operation": "module_roof",
        "material_profile": "concrete_pad_01",
        "grid_units": [2, 1],
        "dimensions_m": {"w": 8.0, "h": 0.4, "d": 4.0},
        "replaces_slots": {"style_modern": "roof_default", "style_military": "roof_default"},
    },
    {
        "module_id": "door_concrete_service_1u",
        "material_family": "concrete",
        "category": "door",
        "style_packs": ["style_modern", "style_military"],
        "operation": "module_door",
        "material_profile": "concrete_pad_01",
        "grid_units": [1, 1],
        "dimensions_m": {"w": 1.4, "h": 2.4, "d": 0.25},
        "replaces_slots": {"style_modern": "door_default", "style_military": "door_default"},
    },
    {
        "module_id": "win_concrete_1u",
        "material_family": "concrete",
        "category": "window",
        "style_packs": ["style_modern"],
        "operation": "module_window",
        "material_profile": "concrete_pad_01",
        "grid_units": [1, 1],
        "dimensions_m": {"w": 1.2, "h": 1.5, "d": 0.12},
        "replaces_slots": {"style_modern": "window_1u"},
    },
    {
        "module_id": "win_concrete_2u",
        "material_family": "concrete",
        "category": "window",
        "style_packs": ["style_modern"],
        "operation": "module_window",
        "material_profile": "concrete_pad_01",
        "grid_units": [2, 1],
        "dimensions_m": {"w": 2.4, "h": 1.5, "d": 0.12},
        "replaces_slots": {"style_modern": "window_2u"},
    },
)
