use crate::knowledge::KnowledgeBase;
use crate::models::DiagnosticIssue;
use crate::models::SourceAnnotation;
use std::collections::BTreeMap;

pub fn resolve_ownership(issues: &mut [DiagnosticIssue], knowledge: &KnowledgeBase) {
    for issue in issues.iter_mut() {
        if issue.owner.is_none() {
            issue.owner = knowledge
                .owner_for_subsystem(&issue.subsystem)
                .or_else(|| default_owner_for_file(&issue.file));
        }
    }
}

pub fn ownership_map_markdown(issues: &[DiagnosticIssue]) -> String {
    let mut by_owner: BTreeMap<String, Vec<&DiagnosticIssue>> = BTreeMap::new();
    for issue in issues {
        let owner = issue
            .owner
            .clone()
            .unwrap_or_else(|| "unassigned".to_string());
        by_owner.entry(owner).or_default().push(issue);
    }

    let mut out = String::from("# Ownership map\n\n");
    out.push_str("> Generated by `rust_engine_orchestrator`. Owners guide agent routing — not auto-fix authority.\n\n");

    for (owner, list) in &by_owner {
        out.push_str(&format!("## {}\n\n", owner));
        for issue in list {
            let touch = if issue.do_not_touch { " **DO NOT TOUCH**" } else { "" };
            out.push_str(&format!(
                "- `{}` L{} — `{}` ({:?}){}\n",
                issue.file, issue.line, issue.symbol, issue.state, touch
            ));
        }
        out.push('\n');
    }
    out
}

fn default_owner_for_file(file: &str) -> Option<String> {
    let norm = file.replace('\\', "/");
    if norm.contains("viewport") || norm.contains("sim_view_sync") {
        Some("viewport_migration_agent".into())
    } else if norm.starts_with("src/render/") {
        Some("render_pipeline_agent".into())
    } else if norm.starts_with("src/gui/") {
        Some("ui_layout_agent".into())
    } else if norm.starts_with("src/dev/stage5") {
        Some("stage5_readiness_agent".into())
    } else {
        None
    }
}

pub fn merge_annotation_owners(
    issues: &mut [DiagnosticIssue],
    annotations: &[SourceAnnotation],
) {
    for issue in issues.iter_mut() {
        if issue.owner.is_some() {
            continue;
        }
        if let Some(ann) = annotations
            .iter()
            .find(|a| a.file == issue.file && a.owner.is_some())
        {
            issue.owner = ann.owner.clone();
        }
    }
}
